/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EntornoGrafico;

import LogicaBecasUniversitarias.Beca;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Manferuz
 */
public class b_Becas extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public b_Becas() {
        initComponents();
        initContenido();
        cargarDatosEnTabla(); // Cargar datos en la tabla al iniciar

    }

    // Método para cargar datos en la tabla
    private void cargarDatosEnTabla() {
        // Obtener el modelo de la tabla
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) becasTable.getModel();
        // Limpiar la tabla antes de agregar nuevos datos
        modelo.setRowCount(0);

        // Crear objetos Beca
        Beca b1 = new Beca("Beca de Excelencia", "Promedio mayor a 90", 92);
        Beca b2 = new Beca("Beca Deportiva", "Ser parte del equipo de fútbol", 70);
        Beca b3 = new Beca("Beca de Investigación", "Participar en un proyecto", 88);
        Beca b4 = new Beca("Beca Cultural", "Participar en actividades culturales", 80);
        Beca b5 = new Beca("Beca de Honor", "Estudiantes destacados en su área", 100);
        Beca b6 = new Beca("Beca de Liderazgo", "Demostrar habilidades de liderazgo", 87);
        Beca b7 = new Beca("Beca de Servicio Comunitario", "Voluntariado comprobado", 82);
        Beca b8 = new Beca("Beca Técnica", "Tener habilidades técnicas", 75);
        Beca b9 = new Beca("Beca de Innovación", "Proyectos innovadores", 85);
        Beca b10 = new Beca("Beca de Desempeño Académico", "Mantener un promedio mínimo", 84);

        // Agregar cada beca a la tabla
        agregarFilaATabla(modelo, b1);
        agregarFilaATabla(modelo, b2);
        agregarFilaATabla(modelo, b3);
        agregarFilaATabla(modelo, b4);
        agregarFilaATabla(modelo, b5);
        agregarFilaATabla(modelo, b6);
        agregarFilaATabla(modelo, b7);
        agregarFilaATabla(modelo, b8);
        agregarFilaATabla(modelo, b9);
        agregarFilaATabla(modelo, b10);
    }

    private void initContenido() {

    }
    


    private void ShowJPanel(JPanel P1) {

        P1.setSize(948, 378);
        P1.setLocation(0, 0);
        Contenido.removeAll();
        Contenido.add(P1, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenido = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        becasTable = new javax.swing.JTable();
        SigBtn = new javax.swing.JButton();

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setPreferredSize(new java.awt.Dimension(948, 478));

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("Becas");
        jLabel29.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jScrollPane1.setForeground(new java.awt.Color(204, 204, 204));

        becasTable.setAutoCreateRowSorter(true);
        becasTable.setBackground(new java.awt.Color(13, 71, 161));
        becasTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        becasTable.setForeground(new java.awt.Color(204, 204, 0));
        becasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre de La Beca", "Requisitos", "Promedio del requisito"
            }
        ));
        becasTable.setGridColor(new java.awt.Color(13, 71, 161));
        becasTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(becasTable);

        SigBtn.setBackground(new java.awt.Color(21, 101, 192));
        SigBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SigBtn.setForeground(new java.awt.Color(255, 255, 255));
        SigBtn.setText("Siguiente");
        SigBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(446, 446, 446))
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SigBtn)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SigBtn)
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SigBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigBtnActionPerformed
        ShowJPanel(new bd_Becas());
    }//GEN-LAST:event_SigBtnActionPerformed
    
    private void agregarFilaATabla(javax.swing.table.DefaultTableModel modelo, Beca beca) {
        // Agregar una fila a la tabla con los datos de la beca
        modelo.addRow(new Object[]{
            beca.getNombreBeca(),
            beca.getRequisitos(),
            beca.getPromedioRequerido()
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JButton SigBtn;
    private javax.swing.JTable becasTable;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
