/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EntornoGrafico;

import LogicaBecasUniversitarias.Beca;
import LogicaBecasUniversitarias.GestorBaseDatosBecas;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class bd_Becas extends javax.swing.JPanel {

    private GestorBaseDatosBecas gestorBD;

    public bd_Becas() {

        // Inicializar el gestor de base de datos
        gestorBD = new GestorBaseDatosBecas(
                "jdbc:mysql://sql10.freesqldatabase.com:3306/sql10759513",
                "sql10759513",
                "nK6aMYm38S"
        );

        initComponents();

    }

    private void ShowJPanel(JPanel P1) {

        P1.setSize(948, 378);
        P1.setLocation(0, 0);
        Contenido.removeAll();
        Contenido.add(P1, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenido = new javax.swing.JPanel();
        txtNombreBeca = new javax.swing.JTextField();
        txtPromedio = new javax.swing.JTextField();
        txtRequisitos = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        btnAnterior = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaBecas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        Contenido.setBackground(new java.awt.Color(255, 255, 255));

        txtNombreBeca.setBackground(new java.awt.Color(25, 118, 210));
        txtNombreBeca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNombreBeca.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreBeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBecaActionPerformed(evt);
            }
        });

        txtPromedio.setBackground(new java.awt.Color(25, 118, 210));
        txtPromedio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPromedio.setForeground(new java.awt.Color(255, 255, 255));

        txtRequisitos.setBackground(new java.awt.Color(25, 118, 210));
        txtRequisitos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRequisitos.setForeground(new java.awt.Color(255, 255, 255));

        btnGuardar.setBackground(new java.awt.Color(13, 71, 161));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnListar.setBackground(new java.awt.Color(13, 71, 161));
        btnListar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("Mostrar Becas añadidas");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnAnterior.setBackground(new java.awt.Color(13, 71, 161));
        btnAnterior.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        txtAreaBecas.setBackground(new java.awt.Color(13, 71, 161));
        txtAreaBecas.setColumns(20);
        txtAreaBecas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAreaBecas.setForeground(new java.awt.Color(204, 204, 0));
        txtAreaBecas.setRows(5);
        jScrollPane1.setViewportView(txtAreaBecas);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Base de Datos de Becas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nombre de la Beca:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Requisitos: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Promedio: ");

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContenidoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListar))
                    .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ContenidoLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(58, 58, 58)
                            .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRequisitos, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtNombreBeca)))
                            .addGap(36, 36, 36)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContenidoLayout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(btnAnterior))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(382, 382, 382))))
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContenidoLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombreBeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRequisitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(ContenidoLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnListar)
                            .addComponent(btnGuardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAnterior))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreBecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBecaActionPerformed

    }//GEN-LAST:event_txtNombreBecaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        guardarBeca();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

        listarBecas();

    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        ShowJPanel(new b_Becas());
    }//GEN-LAST:event_btnAnteriorActionPerformed
    // Método para guardar una nueva beca en la base de datos
    private void guardarBeca() {
        // Obtener datos de los campos de texto
        String nombre = txtNombreBeca.getText().trim(); // Obtiene el nombre de la beca y elimina espacios en blanco
        String req = txtRequisitos.getText().trim(); // Obtiene los requisitos y elimina espacios en blanco
        int prom = 0; // Variable para almacenar el promedio requerido

        try {
            // Intenta convertir el texto del campo de promedio a un entero
            prom = Integer.parseInt(txtPromedio.getText().trim());
        } catch (NumberFormatException nfe) {
            // Si ocurre un error de conversión, muestra un mensaje de error
            JOptionPane.showMessageDialog(this,
                    "Por favor, ingrese un dato válido.", // Mensaje de error
                    "Error", // Título del diálogo
                    JOptionPane.ERROR_MESSAGE); // Tipo de mensaje (error)
            return; // Sale del método sin continuar
        }

        // Verificar si la beca ya existe en la base de datos
        if (gestorBD.existeBeca(nombre)) {
            // Si la beca ya existe, muestra un mensaje de advertencia
            JOptionPane.showMessageDialog(this,
                    "Ya existe la beca '" + nombre + "'.", // Mensaje de advertencia
                    "Beca Existente", // Título del diálogo
                    JOptionPane.WARNING_MESSAGE); // Tipo de mensaje (advertencia)
            return; // Sale del método sin guardar
        }

        // Crear un nuevo objeto Beca con los datos obtenidos
        Beca nueva = new Beca(nombre, req, prom);

        try {
            // Intenta guardar la nueva beca en la base de datos
            gestorBD.guardarBeca(nueva);

            // Muestra un mensaje de éxito si la beca se guardó correctamente
            JOptionPane.showMessageDialog(this,
                    "Beca agregada exitosamente, revisar en la base de datos :)", // Mensaje de éxito
                    "Beca Guardada", // Título del diálogo
                    JOptionPane.INFORMATION_MESSAGE); // Tipo de mensaje (información)

            // Limpiar los campos de texto después de guardar
            txtNombreBeca.setText(""); // Limpia el campo de nombre
            txtRequisitos.setText(""); // Limpia el campo de requisitos
            txtPromedio.setText(""); // Limpia el campo de promedio
        } catch (Exception e) {
            // Si ocurre una excepción, muestra un mensaje de error
            JOptionPane.showMessageDialog(this,
                    "No se pudo guardar la beca. Intente nuevamente.", // Mensaje de error
                    "Error al Guardar", // Título del diálogo
                    JOptionPane.ERROR_MESSAGE); // Tipo de mensaje (error)
            e.printStackTrace(); // Opcional: imprime el error en la consola para depuración
        }
    }

// Método para listar todas las becas en el área de texto
    private void listarBecas() {
        // Obtiene la lista de todas las becas de la base de datos
        List<Beca> lista = gestorBD.obtenerTodasLasBecas();
        txtAreaBecas.setText(""); // Limpia el área de texto antes de mostrar las becas

        // Verifica si la lista de becas está vacía
        if (lista.isEmpty()) {
            // Si no hay becas, muestra un mensaje indicando que no hay registros
            txtAreaBecas.append("No hay becas registradas.\n");
        } else {
            // Recorre la lista de becas y las muestra en el área de texto
            for (Beca b : lista) {
                txtAreaBecas.append(
                        "Beca: " + b.getNombreBeca() + "\n" // Nombre de la beca
                        + "Requisitos: " + b.getRequisitos() + "\n" // Requisitos de la beca
                        + "Prom. Req.: " + b.getPromedioRequerido() + "\n\n" // Promedio requerido
                );
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAreaBecas;
    private javax.swing.JTextField txtNombreBeca;
    private javax.swing.JTextField txtPromedio;
    private javax.swing.JTextField txtRequisitos;
    // End of variables declaration//GEN-END:variables
}
