/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EntornoGrafico;
import LogicaBecasUniversitarias.Carrera;
/**
 *
 * @author Manferuz
 */
public class d_Carreras extends javax.swing.JPanel {

    public d_Carreras() {
        initComponents();
        cargarDatosEnTabla();

    }
    private void cargarDatosEnTabla() {
        // Obtener el modelo de la tabla
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TableCarreras.getModel();

        // Limpiar la tabla antes de agregar nuevos datos
        modelo.setRowCount(0);

        // Crear objetos Carrera
        Carrera car1 = new Carrera("Ingeniería de Sistemas", 7, 100);
        Carrera car2 = new Carrera("Ingeniería de Software", 8, 100);
        Carrera car3 = new Carrera("Ingeniería Electrónica", 9, 100);
        Carrera car4 = new Carrera("Ingeniería Mecánica", 7, 100);
        Carrera car5 = new Carrera("Ingeniería Civil", 6, 100);
        Carrera car6 = new Carrera("Ingeniería Industrial", 5, 100);
        Carrera car7 = new Carrera("Ingeniería Ambiental", 4, 100);
        Carrera car8 = new Carrera("Ingeniería en Telecomunicaciones", 8, 100);
        Carrera car9 = new Carrera("Ingeniería en Transporte", 8, 100);
        Carrera car10 = new Carrera("Ingeniería en Energías Renovables", 8, 100);

        // Agregar cada carrera a la tabla
        agregarFilaATabla(modelo, car1);
        agregarFilaATabla(modelo, car2);
        agregarFilaATabla(modelo, car3);
        agregarFilaATabla(modelo, car4);
        agregarFilaATabla(modelo, car5);
        agregarFilaATabla(modelo, car6);
        agregarFilaATabla(modelo, car7);
        agregarFilaATabla(modelo, car8);
        agregarFilaATabla(modelo, car9);
        agregarFilaATabla(modelo, car10);
    }
    private void agregarFilaATabla(javax.swing.table.DefaultTableModel modelo, Carrera carrera) {
        // Agregar una fila a la tabla con los datos de la carrera
        modelo.addRow(new Object[]{
            carrera.getNombreCarrera(),
            carrera.getNroSemestres(),
            
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCarreras = new javax.swing.JTable();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(948, 478));

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("Carreras");
        jLabel29.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        TableCarreras.setBackground(new java.awt.Color(13, 71, 161));
        TableCarreras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TableCarreras.setForeground(new java.awt.Color(204, 204, 0));
        TableCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre de la Carrera", "Semestres"
            }
        ));
        jScrollPane1.setViewportView(TableCarreras);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addComponent(jLabel29)
                .addContainerGap(458, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableCarreras;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
