/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EntornoGrafico;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Manferuz
 */
public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        initContenido();
    }
    private void initContenido(){
        ShowJPanel(new a_inicio());
     
    }
   
    private void ShowJPanel (JPanel P1){
        
        P1.setSize(948, 378);
        P1.setLocation(0,0);
        Contenido.removeAll();
        Contenido.add(P1, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
        
     
        
        
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        MenuSiglaEMI = new javax.swing.JLabel();
        MenuSeparador = new javax.swing.JSeparator();
        BtnProblemas = new javax.swing.JButton();
        BtnInicio = new javax.swing.JButton();
        BtnBecas = new javax.swing.JButton();
        BtnCarreras = new javax.swing.JButton();
        BtnEstudiantes = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        MensajeHeader1 = new javax.swing.JLabel();
        MensajeHeader2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));

        Menu.setBackground(new java.awt.Color(13, 71, 161));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuSiglaEMI.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MenuSiglaEMI.setForeground(new java.awt.Color(255, 255, 255));
        MenuSiglaEMI.setText("EMI");
        Menu.add(MenuSiglaEMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        MenuSeparador.setPreferredSize(new java.awt.Dimension(50, 5));
        Menu.add(MenuSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 20));

        BtnProblemas.setBackground(new java.awt.Color(21, 101, 192));
        BtnProblemas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnProblemas.setForeground(new java.awt.Color(255, 255, 255));
        BtnProblemas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Problemas.png"))); // NOI18N
        BtnProblemas.setText("Problemas Resueltos");
        BtnProblemas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnProblemas.setBorderPainted(false);
        BtnProblemas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnProblemas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnProblemas.setIconTextGap(13);
        BtnProblemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProblemasActionPerformed(evt);
            }
        });
        Menu.add(BtnProblemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 240, 59));

        BtnInicio.setBackground(new java.awt.Color(21, 101, 192));
        BtnInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnInicio.setForeground(new java.awt.Color(255, 255, 255));
        BtnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inicio.png"))); // NOI18N
        BtnInicio.setText("Inicio");
        BtnInicio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnInicio.setBorderPainted(false);
        BtnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnInicio.setIconTextGap(13);
        BtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInicioActionPerformed(evt);
            }
        });
        Menu.add(BtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 59));

        BtnBecas.setBackground(new java.awt.Color(21, 101, 192));
        BtnBecas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBecas.setForeground(new java.awt.Color(255, 255, 255));
        BtnBecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file-chart.png"))); // NOI18N
        BtnBecas.setText("Becas");
        BtnBecas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnBecas.setBorderPainted(false);
        BtnBecas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBecas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBecas.setIconTextGap(13);
        BtnBecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBecasActionPerformed(evt);
            }
        });
        Menu.add(BtnBecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 240, 59));

        BtnCarreras.setBackground(new java.awt.Color(21, 101, 192));
        BtnCarreras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCarreras.setForeground(new java.awt.Color(255, 255, 255));
        BtnCarreras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Carreras.png"))); // NOI18N
        BtnCarreras.setText("Carreras");
        BtnCarreras.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnCarreras.setBorderPainted(false);
        BtnCarreras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCarreras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnCarreras.setIconTextGap(13);
        BtnCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarrerasActionPerformed(evt);
            }
        });
        Menu.add(BtnCarreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 240, 59));

        BtnEstudiantes.setBackground(new java.awt.Color(21, 101, 192));
        BtnEstudiantes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnEstudiantes.setForeground(new java.awt.Color(255, 255, 255));
        BtnEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Estudiantes.png"))); // NOI18N
        BtnEstudiantes.setText("Estudiantes");
        BtnEstudiantes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnEstudiantes.setBorderPainted(false);
        BtnEstudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEstudiantes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnEstudiantes.setIconTextGap(13);
        BtnEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEstudiantesActionPerformed(evt);
            }
        });
        Menu.add(BtnEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 59));

        Header.setBackground(new java.awt.Color(25, 118, 210));

        MensajeHeader1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MensajeHeader1.setForeground(new java.awt.Color(255, 255, 255));
        MensajeHeader1.setText("Sistema de Registro y Monitoreo de Becas Universitarias");

        MensajeHeader2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MensajeHeader2.setForeground(new java.awt.Color(255, 255, 255));
        MensajeHeader2.setText("ESCUELA MILITAR DE INGENIERÍA");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EMI.png"))); // NOI18N

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(MensajeHeader1))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(MensajeHeader2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(MensajeHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(MensajeHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        Contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnProblemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProblemasActionPerformed
       ShowJPanel(new e_Problemas());
    }//GEN-LAST:event_BtnProblemasActionPerformed

    private void BtnBecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBecasActionPerformed
        ShowJPanel(new b_Becas());
    }//GEN-LAST:event_BtnBecasActionPerformed

    private void BtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInicioActionPerformed
        ShowJPanel(new a_inicio());
    }//GEN-LAST:event_BtnInicioActionPerformed

    private void BtnCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarrerasActionPerformed
        ShowJPanel(new d_Carreras());
    }//GEN-LAST:event_BtnCarrerasActionPerformed

    private void BtnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEstudiantesActionPerformed
        ShowJPanel(new c_Estudiantes());
    }//GEN-LAST:event_BtnEstudiantesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
     
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBecas;
    private javax.swing.JButton BtnCarreras;
    private javax.swing.JButton BtnEstudiantes;
    private javax.swing.JButton BtnInicio;
    private javax.swing.JButton BtnProblemas;
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel MensajeHeader1;
    private javax.swing.JLabel MensajeHeader2;
    private javax.swing.JPanel Menu;
    private javax.swing.JSeparator MenuSeparador;
    private javax.swing.JLabel MenuSiglaEMI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
